version: '2'

services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile
    image: stiles/docker-transmission-armhf
    container_name: transmission_container
    restart: always
    ports:
      - '9091:9091'
      - '52309:52309'
    volumes:
      - "./config:/config"
      - mediacentervolume:/downloads
      - mediacentervolume:/downloads
    env_file: 
      - ./common.env
    network_mode: "host"

volumes:
  mediacentervolume:
    external: true
