version: '2'

services:
  transmission:
    build:
      context: .
      dockerfile: Dockerfile
    image: stiles/docker-transmission-armhf
    container_name: transmission_container_compose
    restart: always
    ports:
      - '9091:9091'
      - '52309:52309'
    volumes:
      - "./config:/config"
      - /torrents:/downloads
      - /torrents:/watch
    env_file: 
      - ./common.env
    network_mode: "host"
