version: '2'

services:
  transmission:
          #    build:
          #      context: .
          #      dockerfile: Dockerfile
    image: lsioarmhf/transmission
    container_name: transmission_container_compose
    restart: always
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    volumes:
      - "./config:/config"
      - "/torrents:/downloads"
      - "/torrents:/watch"
    env_file: 
      - ./common.env
    network_mode: "host"
